/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Stockregister;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author King Vincent
 */
public class BillwiseSearch extends javax.swing.JFrame {

    /**
     * Creates new form BillwiseSearch
     */
    DefaultComboBoxModel  model1;
      DefaultComboBoxModel  model2;
    public BillwiseSearch() {
        initComponents();
        result=getDataBase();
         tokenizer(result);
        
    }Connection con=null;
Statement stmt=null;
ResultSet rs=null;
boolean flag=false;
String message="";
String message1="";
String result="";
String result1="";
    StringTokenizer st;
    String pdate,items,supname,sbillno,squantity,sstusing,sstnew,ssttotal,stotalamt,samt;
    int billno,quantity,stusing,stnew,sttotal,amt;
    double totalamt;
   /* private void combosearch(){
        Connection con=null;
         PreparedStatement pst=null;
         ResultSet rs=null;
        try{
           Class.forName("com.mysql.jdbc.Driver");
           con=DriverManager.getConnection("jdbc:mysql:///user","root","admin");
           String sql="select item from stock";
           pst=con.prepareStatement(sql);
           rs=pst.executeQuery();
           while(rs.next()){
               String name=rs.getString("item");
               combosearch.addItem(name);
           }
        }
        catch(Exception e){
      JOptionPane.showMessageDialog(null,e);
        }
    }*/

  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        combosearch = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        combobill = new javax.swing.JComboBox<>();
        search = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        purchasedate = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        sup = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cost = new javax.swing.JTextField();
        no = new javax.swing.JLabel();
        Stock = new javax.swing.JLabel();
        Using = new javax.swing.JLabel();
        use = new javax.swing.JTextField();
        newavai = new javax.swing.JLabel();
        newavail = new javax.swing.JTextField();
        tsp = new javax.swing.JLabel();
        Totalstock = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        quan = new javax.swing.JTextField();
        total = new javax.swing.JLabel();
        totalcost = new javax.swing.JTextField();
        BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        jLabel1.setText("Select Item");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, -1, -1));

        combosearch.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combosearchItemStateChanged(evt);
            }
        });
        combosearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combosearchActionPerformed(evt);
            }
        });
        getContentPane().add(combosearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 430, 30));

        jLabel2.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        jLabel2.setText("Select Bill No");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, -1, -1));

        combobill.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combobillItemStateChanged(evt);
            }
        });
        combobill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combobillActionPerformed(evt);
            }
        });
        getContentPane().add(combobill, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 430, 30));

        search.setFont(new java.awt.Font("Good Times", 1, 24)); // NOI18N
        search.setText("SEARCH");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        getContentPane().add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 160, 170, 30));

        back.setFont(new java.awt.Font("Good Times", 1, 24)); // NOI18N
        back.setText("BACK");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 210, 170, 30));

        jLabel3.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        jLabel3.setText("Purchase Date");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        purchasedate.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        purchasedate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purchasedateActionPerformed(evt);
            }
        });
        getContentPane().add(purchasedate, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 620, 30));

        jLabel4.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        jLabel4.setText("Suppliers");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, -1, -1));

        sup.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        getContentPane().add(sup, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, 620, 30));

        jLabel5.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        jLabel5.setText("Cost");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 440, 90, -1));

        cost.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        cost.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                costFocusLost(evt);
            }
        });
        cost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                costActionPerformed(evt);
            }
        });
        getContentPane().add(cost, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 440, 160, 30));

        no.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        no.setText("Quantity");
        getContentPane().add(no, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, -1, -1));

        Stock.setFont(new java.awt.Font("Rockwell", 1, 36)); // NOI18N
        Stock.setForeground(new java.awt.Color(0, 102, 153));
        Stock.setText("STOCK");
        getContentPane().add(Stock, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 370, 150, -1));

        Using.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        Using.setText("Using");
        getContentPane().add(Using, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 490, -1, -1));

        use.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        use.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                useActionPerformed(evt);
            }
        });
        getContentPane().add(use, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 490, 160, 30));

        newavai.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        newavai.setText("New");
        getContentPane().add(newavai, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 490, 60, -1));

        newavail.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        getContentPane().add(newavail, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 490, 160, 30));

        tsp.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        tsp.setText("Total Stock");
        getContentPane().add(tsp, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 490, 150, -1));

        Totalstock.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        getContentPane().add(Totalstock, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 490, 160, 30));

        jLabel6.setFont(new java.awt.Font("Rockwell", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 204));
        jLabel6.setText("Search Bill Wise");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, -1, -1));

        quan.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        getContentPane().add(quan, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 440, 160, 30));

        total.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        total.setText("Total Cost");
        getContentPane().add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 440, 120, -1));

        totalcost.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        getContentPane().add(totalcost, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 440, 160, 30));

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Main Screen.png"))); // NOI18N
        getContentPane().add(BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void combosearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combosearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combosearchActionPerformed

    private void costFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_costFocusLost

    }//GEN-LAST:event_costFocusLost

    private void costActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_costActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_costActionPerformed

    private void useActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_useActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_useActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        items= combosearch.getSelectedItem().toString();
           result1=getDataBase1();
        tokenizer1(result1);
        
    }//GEN-LAST:event_searchActionPerformed

    private void combobillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combobillActionPerformed
      
    }//GEN-LAST:event_combobillActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
         dispose();
        new Search().setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void combosearchItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combosearchItemStateChanged
       items= combosearch.getSelectedItem().toString();
      
        System.out.println(items);
        
    }//GEN-LAST:event_combosearchItemStateChanged

    private void combobillItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combobillItemStateChanged
sbillno=combobill.getSelectedItem().toString();
         if(!items.equals("")&&!sbillno.equals("")){
            try{
           con=getConnection();
          if(con==null){
	System.out.println("Connection not found");
	System.exit(0);
	}else{
	stmt = con.createStatement();
	rs = stmt.executeQuery("select * from updatestock where billno='"+sbillno+"'");
		
		 while(rs.next()){   
          billno=rs.getInt(1);
          pdate=rs.getString(2);
          items=rs.getString(3);
          quantity=rs.getInt(4);
          supname=rs.getString(5);
          stusing=rs.getInt(6);
          stnew=rs.getInt(7);
          sttotal=rs.getInt(8);
          totalamt=rs.getDouble(9);
          amt=rs.getInt(10);
          purchasedate.setText(pdate);
          sup.setText(supname);
          squantity=Integer.toString(quantity);
          quan.setText(squantity);
          samt=Integer.toString(amt);
          cost.setText(samt);
          stotalamt=Double.toString(totalamt);
          totalcost.setText(stotalamt);
          sstusing=Integer.toString(stusing);
          use.setText(sstusing);
          sstnew=Integer.toString(stnew);
          newavail.setText(sstnew);
          ssttotal=Integer.toString(sttotal);
          Totalstock.setText(ssttotal);
         
           flag= true;    
       }
       if(flag){
           System.out.println(message1);
	       }
       else{
           flag= false;            
       }

        }
       }catch(Exception e){
           e.printStackTrace();
           System.out.println(e);
       }
             
         }
    }//GEN-LAST:event_combobillItemStateChanged

    private void purchasedateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purchasedateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_purchasedateActionPerformed
            
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BillwiseSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BillwiseSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BillwiseSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BillwiseSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BillwiseSearch().setVisible(true);
            }
    
        });
    }
    private String getDataBase1(){
          try{
           con=getConnection();
          if(con==null){
	System.out.println("Connection not found");
	System.exit(0);
	}else{
	stmt = con.createStatement();
	rs = stmt.executeQuery("select billno from updatestock where items='"+items+"'");
		
		 while(rs.next()){   
         message1+=rs.getString(1)+"@";
          
         
           flag= true;    
       }
       if(flag){
           System.out.println(message1);
	       }
       else{
           flag= false;            
       }

        }
       }catch(Exception e){
           e.printStackTrace();
           System.out.println(e);
       }
        return message1;
    }
    
     private void tokenizer1(String stvalues){
         st=new StringTokenizer(stvalues,"@");
         model2 = (DefaultComboBoxModel) combobill.getModel();
       
        while(st.hasMoreTokens()){
         StringBuilder sb=new StringBuilder();
         String data = (String)st.nextToken();
         sb.append(data);
         System.out.println("Method"+data);
          model2.addElement(data); 
        }
        
     }
    private void tokenizer(String stvalues){
         st=new StringTokenizer(stvalues,"@");
         model1 = (DefaultComboBoxModel) combosearch.getModel();
       
        while(st.hasMoreTokens()){
         StringBuilder sb=new StringBuilder();
         String data = (String)st.nextToken();
         sb.append(data);
         System.out.println("Method"+data);
          model1.addElement(data); 
        }
        
     }
    private String getDataBase(){
          try{
           con=getConnection();
          if(con==null){
	System.out.println("Connection not found");
	System.exit(0);
	}else{
	stmt = con.createStatement();
	rs = stmt.executeQuery("select item from stock ");
		
		 while(rs.next()){   
          message+=rs.getString(1)+"@";
         
           flag= true;    
       }
       if(flag){
           System.out.println(message);
	       }
       else{
           flag= false;            
       }

        }
       }catch(Exception e){
           e.printStackTrace();
           System.out.println(e);
       }
        return message;
    }
    
private Connection getConnection() {
		try {
			Class.forName("com.mysql.jdbc.Driver");
			Connection connection = DriverManager.getConnection(
					"jdbc:mysql://localhost:3306/user", "root", "");
			return connection;
		} catch (Exception ex) {
			ex.printStackTrace();
			System.out.println(ex);
		}
		return null;
	}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JLabel Stock;
    private javax.swing.JTextField Totalstock;
    private javax.swing.JLabel Using;
    private javax.swing.JButton back;
    private javax.swing.JComboBox<String> combobill;
    private javax.swing.JComboBox<String> combosearch;
    private javax.swing.JTextField cost;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel newavai;
    private javax.swing.JTextField newavail;
    private javax.swing.JLabel no;
    private javax.swing.JTextField purchasedate;
    private javax.swing.JTextField quan;
    private javax.swing.JButton search;
    private javax.swing.JTextField sup;
    private javax.swing.JLabel total;
    private javax.swing.JTextField totalcost;
    private javax.swing.JLabel tsp;
    private javax.swing.JTextField use;
    // End of variables declaration//GEN-END:variables
}
