/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Stockregister;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author King Vincent
 */
public class UpdateStock extends javax.swing.JFrame {

    /**
     * Creates new form UpdateStock
     */
    public UpdateStock() {
        initComponents();
        Fillcombo();
        
        
    }
    private void Fillcombo(){
        Connection con=null;
         PreparedStatement pst=null;
         ResultSet rs=null;
        try{
           Class.forName("com.mysql.jdbc.Driver");
           con=DriverManager.getConnection("jdbc:mysql:///user","root","");
           String sql="select item from stock";
           pst=con.prepareStatement(sql);
           rs=pst.executeQuery();
           while(rs.next()){
               String name=rs.getString("item");
               combo.addItem(name);
           }
        }
        catch(Exception e){
      JOptionPane.showMessageDialog(null,e);
        }
    }
    String pdate,items,supname;
        int billlno,stusing,stnew,sttotal,totalamt,amt,qua;
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        billno = new javax.swing.JLabel();
        bilno = new javax.swing.JTextField();
        Date = new javax.swing.JLabel();
        cost = new javax.swing.JTextField();
        Suppliers = new javax.swing.JLabel();
        suppliers = new javax.swing.JTextField();
        Stock = new javax.swing.JLabel();
        use = new javax.swing.JTextField();
        Using = new javax.swing.JLabel();
        newavai = new javax.swing.JLabel();
        newavail = new javax.swing.JTextField();
        tsp = new javax.swing.JLabel();
        Totalstock = new javax.swing.JTextField();
        total = new javax.swing.JLabel();
        totalcost = new javax.swing.JTextField();
        no = new javax.swing.JLabel();
        quantity = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        combo = new javax.swing.JComboBox<>();
        enter = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        date = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        disposed = new javax.swing.JTextField();
        BG1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        billno.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        billno.setText("Bill No");
        getContentPane().add(billno, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        bilno.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        bilno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bilnoActionPerformed(evt);
            }
        });
        getContentPane().add(bilno, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 270, 30));

        Date.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        Date.setText("Date");
        getContentPane().add(Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 440, 80, -1));

        cost.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        cost.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                costFocusLost(evt);
            }
        });
        cost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                costActionPerformed(evt);
            }
        });
        getContentPane().add(cost, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 100, 150, 30));

        Suppliers.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        Suppliers.setText("Suppliers");
        getContentPane().add(Suppliers, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 150, -1));

        suppliers.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        getContentPane().add(suppliers, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 660, 30));

        Stock.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        Stock.setForeground(new java.awt.Color(255, 0, 255));
        Stock.setText("STOCK");
        getContentPane().add(Stock, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 290, 110, -1));

        use.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        use.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                useActionPerformed(evt);
            }
        });
        getContentPane().add(use, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, 80, 30));

        Using.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        Using.setText("Using");
        getContentPane().add(Using, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, -1, -1));

        newavai.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        newavai.setText("New");
        getContentPane().add(newavai, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 350, 60, -1));

        newavail.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        newavail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                newavailFocusLost(evt);
            }
        });
        getContentPane().add(newavail, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 350, 90, 30));

        tsp.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        tsp.setText("Total Stock");
        getContentPane().add(tsp, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 350, 150, -1));

        Totalstock.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        Totalstock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalstockActionPerformed(evt);
            }
        });
        getContentPane().add(Totalstock, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 350, 80, 30));

        total.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        total.setText("Total Cost");
        getContentPane().add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 490, 120, -1));

        totalcost.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        totalcost.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                totalcostFocusLost(evt);
            }
        });
        getContentPane().add(totalcost, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 490, 330, 30));

        no.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        no.setText("Quantity");
        getContentPane().add(no, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 150, -1, -1));

        quantity.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        quantity.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                quantityFocusLost(evt);
            }
        });
        getContentPane().add(quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 150, 150, 30));

        jLabel1.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        jLabel1.setText("Items");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboActionPerformed(evt);
            }
        });
        getContentPane().add(combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 270, 30));

        enter.setFont(new java.awt.Font("Good Times", 1, 18)); // NOI18N
        enter.setText("REGISTER");
        enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterActionPerformed(evt);
            }
        });
        getContentPane().add(enter, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 440, 160, 30));

        exit.setFont(new java.awt.Font("Good Times", 1, 24)); // NOI18N
        exit.setText("EXIT");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 490, 160, 30));

        jLabel2.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        jLabel2.setText("Cost");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 110, 90, 20));

        date.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateActionPerformed(evt);
            }
        });
        getContentPane().add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 440, 330, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Soccer_Ball.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        jLabel3.setText("Disposed");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, -1, -1));

        disposed.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        disposed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disposedActionPerformed(evt);
            }
        });
        getContentPane().add(disposed, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 350, 90, 30));

        BG1.setForeground(new java.awt.Color(255, 0, 204));
        BG1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Main Screen.png"))); // NOI18N
        getContentPane().add(BG1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bilnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bilnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bilnoActionPerformed

    private void useActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_useActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_useActionPerformed

    private void enterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterActionPerformed
         String sbillno = bilno.getText().toString().trim();
         pdate=date.getText().toString().trim();
         billlno=Integer.parseInt(sbillno);
         items=combo.getSelectedItem().toString();
         supname=suppliers.getText().toString().trim();
         String sstusing=use.getText().toString().trim();
         stusing=Integer.parseInt(sstusing);
         String sstnew=newavail.getText().toString().trim();
         stnew=Integer.parseInt(sstnew);
         //String ssttotal=Totalstock.getText().toString().trim();
        // sttotal=Integer.parseInt(ssttotal);
         Connection con=null;
         PreparedStatement pst=null;
         ResultSet rs=null;
        try{
           Class.forName("com.mysql.jdbc.Driver");
           con=DriverManager.getConnection("jdbc:mysql:///user","root","");
           Statement stmt=null;
           stmt = con.createStatement();
           int i = stmt.executeUpdate("insert into updatestock values('"+billlno+"','"+pdate+"','"+items+"','"+qua+"','"+supname+"','"+stusing+"','"+stnew+"','"+sttotal+"','"+totalamt+"','"+amt+"')");
           if(i>0){
                    
                        System.out.println("Values are inserted....");
                        bilno.setText(null);
                        date.setText(null);
                        suppliers.setText(null);
                        use.setText(null);
                        newavail.setText(null);
                        Totalstock.setText(null);
                        totalcost.setText(null);
                        cost.setText(null);
                        quantity.setText(null);
                        disposed.setText(null);
                        JOptionPane.showMessageDialog(rootPane, "Stock Registered" );
                        }else{
		System.out.println("Values are not inserted....");
                JOptionPane.showMessageDialog(rootPane, "Stock Not Registered" );
		}
        }
        catch(HeadlessException | ClassNotFoundException | SQLException e){
      JOptionPane.showMessageDialog(null,e);
        }
                        
         
    }//GEN-LAST:event_enterActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        dispose();
    }//GEN-LAST:event_exitActionPerformed

    private void comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboActionPerformed

    private void dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateActionPerformed

    private void totalcostFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_totalcostFocusLost
       
    }//GEN-LAST:event_totalcostFocusLost

    private void costActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_costActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_costActionPerformed

    private void costFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_costFocusLost
       
    }//GEN-LAST:event_costFocusLost

    private void quantityFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_quantityFocusLost
         String samt=cost.getText().toString().trim();
         amt=Integer.parseInt(samt);
        String squantity=quantity.getText().toString().trim();
        qua=Integer.parseInt(squantity);
          totalamt=amt*qua;
        String stotalamt=Integer.toString(totalamt);
        totalcost.setText(stotalamt);
    }//GEN-LAST:event_quantityFocusLost

    private void disposedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disposedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_disposedActionPerformed

    private void TotalstockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalstockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TotalstockActionPerformed

    private void newavailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_newavailFocusLost
        int dis=0;
        String dispose=disposed.getText().toString().trim();
              dis=Integer.parseInt(dispose);
        String sn=newavail.getText().toString().trim();
        int snew=Integer.parseInt(sn);
        String su=use.getText().toString().trim();
        int suse=Integer.parseInt(su);
        sttotal=(suse-dis)+snew;
        String s=Integer.toString(sttotal);
        Totalstock.setText(s);
    }//GEN-LAST:event_newavailFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateStock().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG1;
    private javax.swing.JLabel Date;
    private javax.swing.JLabel Stock;
    private javax.swing.JLabel Suppliers;
    private javax.swing.JTextField Totalstock;
    private javax.swing.JLabel Using;
    private javax.swing.JLabel billno;
    private javax.swing.JTextField bilno;
    private javax.swing.JComboBox<String> combo;
    private javax.swing.JTextField cost;
    private javax.swing.JTextField date;
    private javax.swing.JTextField disposed;
    private javax.swing.JButton enter;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel newavai;
    private javax.swing.JTextField newavail;
    private javax.swing.JLabel no;
    private javax.swing.JTextField quantity;
    private javax.swing.JTextField suppliers;
    private javax.swing.JLabel total;
    private javax.swing.JTextField totalcost;
    private javax.swing.JLabel tsp;
    private javax.swing.JTextField use;
    // End of variables declaration//GEN-END:variables
}
